// import { Geist, Geist_Mono, Inter } from "next/font/google";
// import AppProviders from "@/components/AppProviders";
// import { cn } from "@/lib/utils";

// const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Authentication",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={cn(
//         "h-full",
//         "antialiased",
//         geistSans.variable,
//         geistMono.variable,
//         "font-sans",
//         inter.variable,
//         "dark",
//       )}
//     >
//       <body className="min-h-full flex flex-col dark:bg-gray-800">
//         <AppProviders>{children}</AppProviders>
//       </body>
//     </html>
//   );
// }

// app/(public)/layout.jsx
import HeaderLayout from "@/components/layout/HeaderLayoyt";

export default function PublicLayout({ children }) {
  return (
    <div className="flex flex-col min-h-screen">
      <HeaderLayout>
        <main className="flex-1">{children}</main>
      </HeaderLayout>
    </div>
  );
}
